db: tester01
server:
  port: 8888
  servlet:
    context-path: /api/v1
    session:
      cookie:
        name: BIUSID
spring:
  profiles:
    active: dev
    include: druid,mybatisplus,shiro
  redis:
    host: localhost
    port: 6379
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.202.4.58:3306/${db}?characterEncoding=UTF-8&useSSL=false
    username: tester01
    password: tester01
logging:
  path: ./logs
  level:
    com.abc.dao: debug
