db: tester01
server:
  port: 8888
  servlet:
    context-path: /
    session:
      cookie:
        name: BIUSID
spring:
  redis:
    host: localhost
    port: 6379
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.202.4.58:3306/${db}?characterEncoding=UTF-8&useSSL=false
    username: tester01
    password: tester01
    druid:
      initialSize: 20
      minIdle: 20
      maxWait: 60000
      maxActive: 20
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
logging:
  path: ./logs
  level:
    com.abc.dao: debug
